### ISSUE TITLE
[Bug report]About bot shows incorrect input status

### ISSUE THREAD

**Issue by AlanBacker** [Echoshard/Gemini_Discordbot#4]
Hello, developers. When I was using the program for this project, I found that after the robot answered my question, there was a chance that the input status would still display "xxx is being input...". The bug was as shown in the picture (the language is Chinese, but it is obvious that, The robot has answered the question but there is still a chance that it will display "Inputting...")
![image](https://github.com/Echoshard/Gemini_Discordbot/assets/53960149/0a95774e-b708-43c0-bef3-3457648eef40)
I hope you can fix this little bug, which will definitely make this program more perfect, thank you!

**Comment by Echoshard** [comment]
Sorry I really don't understand what you are asking. Are you talking about the typing text?  And the fact that it does not stop right away?

**Comment by AlanBacker** [comment]
It may be difficult to explain. First of all, we know that when a user enters text in discord, others can see the typing status. This function is also implemented in your robot project. Generally speaking, after the robot answers the question, when others see the robot's input status, it will change from "typing" to not showing "typing". But I found that there is a probability that even after the robot has answered all the questions, when others see the typing status of the robot, it will still show "typing"..

**Comment by Echoshard** [comment]
The typing is purely for aesthetic. The typing concept is designed because in general one person is typing on the other end. Something humans do.  A discord bot however can type to several different people at once. (Humans can't do)

  You can just comment that part out  `async with message.channel.typing():` fix the indent  and have it add reactions when it's done.   `await message.add_reaction('✅')`
